### ISSUE TITLE
你好，我也总尝试e480黑苹果

### ISSUE THREAD

**Issue by hoffmannchen** [aliyoge/Hackintosh-ThinkPad-E480#1]
你好，搜索了好久，终于找到e480的hackintosh!  我原本是淘宝上付费黑的10.12.6,现在基本能用.主要问题是风扇老转个不停，另外接显示器分辨率只有1080P。请问我用你的文件直接替换efi的文件夹就可以了吗？你这个配置完成度有多少？由于是初学，还请不吝指教。

**Comment by aliyoge** [comment]
我一直是用于日常使用，CPU是用的原生电源管理，变频正常，风扇不会一直响，可以正常休眠。外接显示器我是用的1080P的，其他分辨率没试过，不过应该是没有问题。网卡我换成了BCM94352Z，另外我的MAC是单独安装在第二块硬盘上的。除了直接替换EFI文件夹，其他还有一些操作具体看说明。

**Comment by hoffmannchen** [comment]
昨晚用你的配置直接替换了。总体比之前的付费安装的要好。现在有以下问题，第一：显卡显示是hd620，但显存只有7m，把原来的设定值改为0x59160000似乎正常了。第二：电脑直接合盖似乎只是关闭显示，一直没有休眠。手工按电源键可以休眠并唤醒。很奇怪的是一开始发热和风扇声都很完美，但重新开机后又是风扇呼呼的响，是不是要单独设置一下屏蔽独显？还有些小问题如调节亮度的按键没反应。总的来说比之前好用多了，谢谢！

**Comment by aliyoge** [comment]
@hoffmannchen 我那里面有屏蔽独显的SSDT，我的机器参数是i5-8250、8G、256G这一款。

**Comment by aliyoge** [comment]
@hoffmannchen 你应该要重新给你自己的DSDT打补丁，以为我的BIOS信息表跟你的不一样。

**Comment by terrydash** [comment]
i7款 应该因为DSDT不同 无法开机

**Comment by hoffmannchen** [comment]
还是我！ 用了新的EFI更爽了，就是触摸板drag and drop不行，无法拖拉。请问您怎么解决的？

**Comment by aliyoge** [comment]
@hoffmannchen 你在试试新的看看

**Comment by python8384** [comment]
大神，我使用你的EFI替换了，替他的用的还算正常，就是声卡不能驱动，没有声音，能不能帮忙指导一下，谢谢。

**Comment by aliyoge** [comment]
@python8384 声卡直接注入3就行了。

```
<key>Audio</key>
		<dict>
			<key>Inject</key>
			<integer>3</integer>
			<key>ResetHDA</key>
			<true/>
		</dict>
```

**Comment by stupidido** [comment]
您好 我想请教一下 我使用了您的EFI，但是开机之后会显卡报错。我也使用了您的屏蔽aml但是还是无法解决报错问题。请问最近有遇到过这方面的情况吗？ 我的配置是i5 8250u 16G 1T SSD RX550
