### ISSUE TITLE
目前遇到的问题

### ISSUE THREAD

**Issue by eurly** [aliyoge/Hackintosh-ThinkPad-E480#12]
1、待机后掉电严重；晚上8点待机，第二天早上只有70%的电；
2、待机会失败的情况，晚上8点待机，第二天电量为1%了，系统自动关机了；
3、触摸板有时候会失灵，单指无法移动光标，需要改成双指，但双指只实现了单指的功能，要想用双指的功能，需要用三指，要三指的功能又需要换成四指，以此类推；
4、待机后打开笔记本盖板后，屏幕不亮，这时候按下键盘，耳机中会有声音反馈；

**Comment by aliyoge** [comment]
更新一下，修复了休眠问题。

**Comment by SukkaW** [comment]
> 3、触摸板有时候会失灵，单指无法移动光标，需要改成双指，但双指只实现了单指的功能，要想用双指的功能，需要用三指，要三指的功能又需要换成四指，以此类推；

VoodooPS2 没有 attach 到 ThinkPad ClickPad 导致的。如果去看一下 `ioreg` 会发现，VoodooInput 里模拟的 I2C 蓝牙触控板 attach 到硬件设备了。

@aliyoge 这个需要带个 ClickPad 的 Hotpatch。

**Comment by aliyoge** [comment]
> > 3、触摸板有时候会失灵，单指无法移动光标，需要改成双指，但双指只实现了单指的功能，要想用双指的功能，需要用三指，要三指的功能又需要换成四指，以此类推；
> 
> VoodooPS2 没有 attach 到 ThinkPad ClickPad 导致的。如果去看一下 `ioreg` 会发现，VoodooInput 里模拟的 I2C 蓝牙触控板 attach 到硬件设备了。
> 
> @aliyoge 这个需要带个 ClickPad 的 Hotpatch。

我也碰到过这个问题，一般是在睡眠之后，我在设置里面随便改一下触摸板的选项，然后改回来，触摸板就会被激活。

**Comment by SukkaW** [comment]
@aliyoge 

ThinkPad 机型触摸板的很多特殊问题，VoodooPS2 里都修复了的，但是如果要调用 VoodooPS2 里的相关修复，必须在 SSDT 里指明当前触摸板型号是 Lenovo ClickPad。

最近我还在研究 Fn 快捷键，到时候也许可以一起开个 Pull Request。

**Comment by chendafa** [comment]
首先非常感谢 @aliyoge 无私分享。我是i5 8250u CPU，CPU频率基本上都是 2.3 没有什么波动。

**Comment by SukkaW** [comment]
> 首先非常感谢 @aliyoge 无私分享。我是i5 8250u CPU，CPU频率基本上都是 2.3 没有什么波动。

@chendafa 

aliyoge 也是 i5-8250u，所以他生成的 CPUFriendData 应该是在你设备上通用的。
检查一下 X86、LPC 注入成功没有，我自己生成变频后的 i7-8550U 空闲频率都能降到 1 以下的。

**Comment by chendafa** [comment]
> > 首先非常感谢 @aliyoge 无私分享。我是i5 8250u CPU，CPU频率基本上都是 2.3 没有什么波动。
> 
> @chendafa
> 
> aliyoge 也是 i5-8250u，所以他生成的 CPUFriendData 应该是在你设备上通用的。
> 检查一下 X86、LPC 注入成功没有，我自己生成变频后的 i7-8550U 空闲频率都能降到 1 以下的。

怎么查看 X86、LPC有没有注入成功

**Comment by aliyoge** [comment]
@chendafa 
用这个命令`kextstat | grep X86`看有没有`X86PlatformPlugin`

**Comment by chendafa** [comment]
今天从 10.15.3 升级到 10.15.4 (19E287)   发现启动需要插拔一下外接显示器的HDMI线

**Comment by xqdxqd** [comment]
S3睡眠后Fn快捷键失效以及电池状态不更新，E480也有这个问题么
