### ISSUE TITLE
config.plist好像有问题

### ISSUE THREAD

**Issue by Raphaelren** [aliyoge/Hackintosh-ThinkPad-E480#13]
刚换OC第时候出现声卡不能驱动第情况,把config.plist第500行“<key>PciRoot(0x0)/Pci(0x1f, 0x3)</key>” 去掉0x3前面的空格就好了

**Comment by lokig2020** [comment]
去掉空格还是没用，必须调整一下音量
还有，为什么亮度快捷键没用用
