### ISSUE TITLE
4k over USB-C

### ISSUE THREAD

**Issue by kyvaith** [aliyoge/Hackintosh-ThinkPad-E480#17]
Hi,

Should I except 4k over USB-C to work? I'm unable to get full resolution. Thanks for any help.

**Comment by raydoom** [comment]
Could you get 4k@60hz over USB-C in win10.
@kyvaith

**Comment by kyvaith** [comment]
Sure.

**Comment by raydoom** [comment]
May some help
`https://blog.skk.moe/post/thinkpad-e480-hackintosh-efi/`
> HDMI 1.4 接口由集成显卡驱动，最高支持 2K@60Hz 和 4K@30Hz ，已通过定制显示接口修复紫屏问题，教程请看我的另一篇文章「使用 Hackintool 修复黑苹果 Intel 核显驱动外部显示器紫屏问题」。Type-C 接口定制输出类型为 DisplayPort，最高支持 4K@60Hz 输出。

**Comment by kyvaith** [comment]
After boosting DVMT works well.
