### ISSUE TITLE
10.14.6休眠之后快捷键用不了，usb好像也有问题

### ISSUE THREAD

**Issue by herbiel** [aliyoge/Hackintosh-ThinkPad-E480#18]
10.14.6休眠之后快捷键用不了，usb好像也有问题

**Comment by aliyoge** [comment]
快捷键我没有使用过，如果usb有问题，最好自己定制一下。
已经升级到10.15了，10.14没有做过测试。

**Comment by GrantSJ** [comment]
快捷键可以考虑借助Karabiner第三方的app，非常实用
