### ISSUE TITLE
声卡没法驱动，试过其它id无果

### ISSUE THREAD

**Issue by ebfood** [aliyoge/Hackintosh-ThinkPad-E480#19]
HDMI有声音输出，音响没有

**Comment by ebfood** [comment]
试过id3，14，15，21

**Comment by aliyoge** [comment]
@ebfood 我这边hdmi输出声音应该是可以的，年会抽奖的时候用我的电脑投屏过。
之后就没有测试过了。

**Comment by ebfood** [comment]
@aliyoge 只有插hdmi才能从hdmi输出声音，hdmi是正常的，拔了就不行了

**Comment by iarbor** [comment]
声卡驱动需要是冷启动进OC启动,如果是先进入Windows,再热启动进OC就会无法驱动内置声卡。

**Comment by ebfood** [comment]
> 声卡驱动需要是冷启动进OC启动,如果是先进入Windows,再热启动进OC就会无法驱动内置声卡。

感谢！解决了！
