### ISSUE TITLE
Question: which SSD is mounted in your machine?

### ISSUE THREAD

**Issue by w00zie** [aliyoge/Hackintosh-ThinkPad-E480#2]
Hi, thanks for the repo.

I own a T480 and I was wondering which model is your SSD.
A Lenovo-branded NVME SSD is mounted on my machine, is it the same as yours?

**Comment by aliyoge** [comment]
I use [TOSHIBA TR200](https://item.jd.com/5724596.html) for MacOS, and Lenovo-branded NVME SSD for Windows 10.
