### ISSUE TITLE
切换双系统导致声卡驱动失效

### ISSUE THREAD

**Issue by Lintao-Zeng** [aliyoge/Hackintosh-ThinkPad-E480#21]
你好，我装了windows和黑苹果双系统，用的是OC引导，但是在每次用完windows后切换到黑苹果系统时，黑苹果系统的声卡驱动就会失效，使用kextload和kextutil命令均无效，只有强制关机或断电才能使驱动恢复，不知道是什么原因造成的，请问有办法解决吗？

**Comment by aliyoge** [comment]
不好意思，我没有使用双系统，暂时没法测试此问题。

**Comment by Lintao-Zeng** [comment]
谢谢，我问了Sukka，他说无解，只能断电或强制重启------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jordy&amp;nbsp;Wong&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月12日(星期一) 上午9:58
收件人:&nbsp;&quot;aliyoge/Hackintosh-ThinkPad-E480&quot;<Hackintosh-ThinkPad-E480@noreply.github.com&gt;;
抄送:&nbsp;&quot;zenglintao&quot;<2534324260@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aliyoge/Hackintosh-ThinkPad-E480] 切换双系统导致声卡驱动失效 (#21)
