### ISSUE TITLE
英特尔wifi现在已经一个大佬搞定了，可以再efi里面加一下吗

### ISSUE THREAD

**Issue by silentchild** [aliyoge/Hackintosh-ThinkPad-E480#25]
驱动地址：https://github.com/OpenIntelWireless/itlwm/releases

**Comment by aliyoge** [comment]
如果你那边用的上的话，麻烦你自己下载本仓库之后手动替换一下驱动，然后改一下config就行了。
因为我这边已经没有那个网卡，没有办法做测试。

**Comment by silentchild** [comment]
> 如果你那边用的上的话，麻烦你自己下载本仓库之后手动替换一下驱动，然后改一下config就行了。
> 因为我这边已经没有那个网卡，没有办法做测试。

好的 谢谢

**Comment by DakenYue** [comment]
> > 如果你那边用的上的话，麻烦你自己下载本仓库之后手动替换一下驱动，然后改一下config就行了。
> > 因为我这边已经没有那个网卡，没有办法做测试。
> 
> 好的 谢谢

您好，请问您驱动成功了吗，我只需要将kext文件放入kexts目录即可吗
