### ISSUE TITLE
Are there any updates to big sur?

### ISSUE THREAD

**Issue by mahronid** [aliyoge/Hackintosh-ThinkPad-E480#26]
Failed, early kernel panic

**Comment by aliyoge** [comment]
sorry, I haven't upgraded yet. I will try In a few days. You are also welcome to share.

**Comment by mahronid** [comment]
Hey, I've updated OpenCore to 0.6.5 and kexts. Not yet tested on BigSur (soon).
https://github.com/mahronid/hackintosh-thinkpad-e480.git

**Comment by mahronid** [comment]
> Hey, I've updated OpenCore to 0.6.5 and kexts. Not yet tested on BigSur (soon).
> https://github.com/mahronid/hackintosh-thinkpad-e480.git

Now it's support MacOS 11.1 Big Sur.
