### ISSUE TITLE
My experience (different model) and issues (4K display, TrackPoint, GeekBench)

### ISSUE THREAD

**Issue by ghost** [aliyoge/Hackintosh-ThinkPad-E480#3]
Model: i5-8250U, UHD 620, no d-GPU

1. remove `ACPI/patched/DSDT.aml` or it won't boot. (SSDT* is generic)
2. get *.dsl according to https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/
3. fix syntax and apply battery patch for DSDT.dsl, generate DSDT.aml and put it in `ACPI/patched/`

Question:
- Is there any other patch should I apply?

Issues:
- 4K display (over USB-C) cannot achieve native resolution (only 2560x1440 no HiDPI)
  - even after applying https://github.com/Floris497/mac-pixel-clock-patch-V2
- TrackPoint does not work
  - Redownload VoodooPS2Controller.kext makes it work but not smooth.
- GeekBench single-core (3000) is significantly lower than on Windows (3800)
  - multi-core score is matchable to Windows
  - clover `SSDT/Generate/CStates|PState = true`, single-core score goes to 3300

<s>I will continue to investigate those issues.</s> Also thanks for any help.

**Comment by ghost** [comment]
About 4K display: it requires DVMT-prealloc to be set to 64MB or above. The BIOS does not provide this option and it is hard to mod the BIOS. So I have given up.

Reference:
- https://www.elitemacx86.com/threads/guide-how-to-unlock-dvmt-pre-allocated-on-laptops.313/
- https://github.com/daliansky/XiaoMi-Pro/issues/117

**Comment by shilch** [comment]
You can change DVMT. I did it, but it didn't solve my 4k issues either.

**Comment by nikber84** [comment]
> About 4K display: it requires DVMT-prealloc to be set to 64MB or above. The BIOS does not provide this option and it is hard to mod the BIOS. So I have given up.
> 
> Reference:
> 
> * https://www.elitemacx86.com/threads/guide-how-to-unlock-dvmt-pre-allocated-on-laptops.313/
> * [daliansky/XiaoMi-Pro-Hackintosh#117](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/117)



> Model: i5-8250U, UHD 620, no d-GPU
> 
> 1. remove `ACPI/patched/DSDT.aml` or it won't boot. (SSDT* is generic)
> 2. get *.dsl according to https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/
> 3. fix syntax and apply battery patch for DSDT.dsl, generate DSDT.aml and put it in `ACPI/patched/`
> 
> Question:
> 
> * Is there any other patch should I apply?
> 
> Issues:
> 
> * 4K display (over USB-C) cannot achieve native resolution (only 2560x1440 no HiDPI)
>   
>   * even after applying https://github.com/Floris497/mac-pixel-clock-patch-V2
> * TrackPoint does not work
>   
>   * Redownload VoodooPS2Controller.kext makes it work but not smooth.
> * GeekBench single-core (3000) is significantly lower than on Windows (3800)
>   
>   * multi-core score is matchable to Windows
>   * clover `SSDT/Generate/CStates|PState = true`, single-core score goes to 3300
> 
> I will continue to investigate those issues. Also thanks for any help.

Hi. Can you share your EFI folder?

**Comment by SukkaW** [comment]
@ffffwh Which `VoodooPS2Controller` do you use to make trackpoint works?
This one will only make trackpoint itself to work but no touchpad then: https://github.com/acidanthera/VoodooPS2
I could only use this kext to make both of trackpoint and touchpad to work: https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller
