### ISSUE TITLE
E480 with i7 8550U 16GB and dual SSD

### ISSUE THREAD

**Issue by pannik72** [aliyoge/Hackintosh-ThinkPad-E480#4]
Hello

I have managed to install the OSX mojave on the NMVE ssd and copied yoyr efi but it wont boot.
When I use the installation usb I am able to boot the installed OSX.
What are the differences between the two machines?
What should I do in order to boot the system from the hard disk?
I am complete newbie.

Thanks in advance

**Comment by aliyoge** [comment]
@pannik72 My MacOS is installed on the sata ssd and is not installed on the nvme ssd. So I don't know if there is a problem directly on the nvme. There are many problems with installing on nvme.
