### ISSUE TITLE
E480集显版i5 8250u + 8G + 256G NVMe 安装时五国

### ISSUE THREAD

**Issue by firefishREAL** [aliyoge/Hackintosh-ThinkPad-E480#5]
E480集显版i5 8250u + 8G + 256G NVMe，10.14.5安装盘，采用作者大大的efi，报五国错误，能帮忙看下问题吗

![20190606102945](https://user-images.githubusercontent.com/30450982/59002754-100ebb80-8846-11e9-8658-fc949fe7ad45.jpg)

**Comment by firefishREAL** [comment]
我的BIOS 版本是1.12

**Comment by aliyoge** [comment]
@firefishREAL 我的MacOS是直接装在sata固态上的，没有装在nvme固态上。所以我不知道直接在nvme上装是不是有问题。而且你可以先找一个通用配置，能正常引导并且安装之后在替换我这个EFI。

**Comment by firefishREAL** [comment]
能否方便看下您电脑的BIOS版本，可能是BIOS版本不一致导致的冲突

**Comment by 543221947** [comment]
我的也是E480集显版，一样的情况，已经确认了与BIOS版本无关（回滚了BIOS版本情况依旧），删除了 DDGPU 也还是如此，特向楼主寻求帮助，有何良策，先感谢为敬！

**Comment by 543221947** [comment]
方便的话帮我回个邮件 moon.13@qq.com 谢谢！

**Comment by q503200098** [comment]
发现的问题和你的一样，通过黒果小兵的镜像里面的通用efi引导进入的系统，改了作者大大的dsdt为其他任意名字，现在能引导进入系统，但是部分功能使用是有问题的，比如蓝牙，目前我还只是个黑苹果的小白，只能停留在别人给efi我用的级别，但是猜测可能是因为dsdt有问题，从网上听说hotpatch方式黑苹果好像dsdt文件就不那么重要。
值得一提的是，我的硬件是i5-8250u 16g运存 512g三星sm951 m.2 nvme固态硬盘 1t机械硬盘 集显版本，期望能有所帮助。

**Comment by aliyoge** [comment]
@firefishREAL @543221947 @q503200098 
安装系统的时候不要使用我的EFI，安装好之后再替换。安装的时候找一个通用配置就可以了，E480的很好驱动。

我的网卡换了，如果你们的网卡跟我不一样，你可以尝试将`AirportBrcmFixup.kext`和`BrcmPatchRAM2.kext`这两个驱动去掉试试。

BIOS版本不一致可能会导致问题，最好的办法是使用[RehabMan](https://github.com/RehabMan/Laptop-DSDT-Patch)的工具选着[battery_Lenovo-X230i.txt](https://github.com/RehabMan/Laptop-DSDT-Patch/blob/master/battery/battery_Lenovo-X230i.txt)配置文件自己打一下补丁。具体教程可以自行搜索一下，非常简单。
