### ISSUE TITLE
Only BCM94352Z is compatible adapter?

### ISSUE THREAD

**Issue by dievdmitry** [aliyoge/Hackintosh-ThinkPad-E480#6]
Hello only BCM94352Z is compatible adapter? May be somebody knew different compatible adapters?

**Comment by aliyoge** [comment]
@dievdmitry sorry, I am not sure. I only know that this can be used.

**Comment by llnnse** [comment]
Did you had to modify your BIOS for that card to work properly or did your ThinkPad came without the wifi-card restriction implemented into the BIOS?

**Comment by aliyoge** [comment]
@tkrtz No need to crack the BIOS. This network card is the official Lenovo model.
