### ISSUE TITLE
E480安装后替换EFI无法开机

### ISSUE THREAD

**Issue by doulchen** [aliyoge/Hackintosh-ThinkPad-E480#7]
您好，我有两台E480笔记本，分别为8代和7代的产品，均为集显
一台为i5-8250U另一台为i3-7020U，第一台配置与你的一样，第二台CPU代数不同外形也有差异。
现在两台替换完EFI后都是同等情况，无法开机，应该是卡在DSDT了。
两台BIOS版本均为1.35，安装Mojave14.6，请问您的BIOS版本是多少？有办法解决无法开机嘛？

**Comment by aliyoge** [comment]
> 您好，我有两台E480笔记本，分别为8代和7代的产品，均为集显
> 一台为i5-8250U另一台为i3-7020U，第一台配置与你的一样，第二台CPU代数不同外形也有差异。
> 现在两台替换完EFI后都是同等情况，无法开机，应该是卡在DSDT了。
> 两台BIOS版本均为1.35，安装Mojave14.6，请问您的BIOS版本是多少？有办法解决无法开机嘛？

@doulchen 首先我的网卡换了，我不确定会不会有影响。如果你的网卡跟我不一样，你可以尝试将`AirportBrcmFixup.kext`和`BrcmPatchRAM2.kext`这两个驱动去掉试试。

BIOS版本不一致可能会导致问题，最好的办法是使用[RehabMan](https://github.com/RehabMan/Laptop-DSDT-Patch)的工具选择[battery_Lenovo-X230i.txt](https://github.com/RehabMan/Laptop-DSDT-Patch/blob/master/battery/battery_Lenovo-X230i.txt)配置文件自己打一下补丁。具体教程可以自行搜索一下，非常简单。

**Comment by doulchen** [comment]
> > 您好，我有两台E480笔记本，分别为8代和7代的产品，均为集显
> > 一台为i5-8250U另一台为i3-7020U，第一台配置与你的一样，第二台CPU代数不同外形也有差异。
> > 现在两台替换完EFI后都是同等情况，无法开机，应该是卡在DSDT了。
> > 两台BIOS版本均为1.35，安装Mojave14.6，请问您的BIOS版本是多少？有办法解决无法开机嘛？
> 
> @doulchen 首先我的网卡换了，我不确定会不会有影响。如果你的网卡跟我不一样，你可以尝试将`AirportBrcmFixup.kext`和`BrcmPatchRAM2.kext`这两个驱动去掉试试。
> 
> BIOS版本不一致可能会导致问题，最好的办法是使用[RehabMan](https://github.com/RehabMan/Laptop-DSDT-Patch)的工具选择[battery_Lenovo-X230i.txt](https://github.com/RehabMan/Laptop-DSDT-Patch/blob/master/battery/battery_Lenovo-X230i.txt)配置文件自己打一下补丁。具体教程可以自行搜索一下，非常简单。

非常感谢你的回复，下面是我通过你回复并操作后得出的一些结果。
在更换DW1820A或者DW1560的情况下仍无法正常卡机，根据rehabman在反编译DSDT并修复电源后可正常启动，电源显示正常，估计是bios的问题或者为机型差异导致的问题。希望以上对你EFI的优化有帮助，再次感谢。
另外有个问题，我现在的键盘大小写灯经常无法正常指示状态，还有静音键的灯会常亮，偶尔FnLock也会常亮，请问你是否有类似情况呢。

**Comment by zhanghanbing1998** [comment]
> > > 您好，我有两台E480笔记本，分别为8代和7代的产品，均为集显
> > > 一台为i5-8250U另一台为i3-7020U，第一台配置与你的一样，第二台CPU代数不同外形也有差异。
> > > 现在两台替换完EFI后都是同等情况，无法开机，应该是卡在DSDT了。
> > > 两台BIOS版本均为1.35，安装Mojave14.6，请问您的BIOS版本是多少？有办法解决无法开机嘛？
> > 
> > 
> > @doulchen 首先我的网卡换了，我不确定会不会有影响。如果你的网卡跟我不一样，你可以尝试将`AirportBrcmFixup.kext`和`BrcmPatchRAM2.kext`这两个驱动去掉试试。
> > BIOS版本不一致可能会导致问题，最好的办法是使用[RehabMan](https://github.com/RehabMan/Laptop-DSDT-Patch)的工具选择[battery_Lenovo-X230i.txt](https://github.com/RehabMan/Laptop-DSDT-Patch/blob/master/battery/battery_Lenovo-X230i.txt)配置文件自己打一下补丁。具体教程可以自行搜索一下，非常简单。
> 
> 非常感谢你的回复，下面是我通过你回复并操作后得出的一些结果。
> 在更换DW1820A或者DW1560的情况下仍无法正常卡机，根据rehabman在反编译DSDT并修复电源后可正常启动，电源显示正常，估计是bios的问题或者为机型差异导致的问题。希望以上对你EFI的优化有帮助，再次感谢。
> 另外有个问题，我现在的键盘大小写灯经常无法正常指示状态，还有静音键的灯会常亮，偶尔FnLock也会常亮，请问你是否有类似情况呢。

你好，我也出现替换EFI后不能开机的情况，能请教一下您是怎么打补丁的吗，我看了很多教程没看懂

**Comment by zhanghanbing1998** [comment]
@doulchen 你好，我也出现替换EFI后不能开机的情况，能请教一下您是怎么打补丁的吗，我看了很多教程没看懂

**Comment by tankoki** [comment]
> > > 您好，我有两台E480笔记本，分别为8代和7代的产品，均为集显
> > > 一台为i5-8250U另一台为i3-7020U，第一台配置与你的一样，第二台CPU代数不同外形也有差异。
> > > 现在两台替换完EFI后都是同等情况，无法开机，应该是卡在DSDT了。
> > > 两台BIOS版本均为1.35，安装Mojave14.6，请问您的BIOS版本是多少？有办法解决无法开机嘛？
> > 
> > 
> > @doulchen 首先我的网卡换了，我不确定会不会有影响。如果你的网卡跟我不一样，你可以尝试将`AirportBrcmFixup.kext`和`BrcmPatchRAM2.kext`这两个驱动去掉试试。
> > BIOS版本不一致可能会导致问题，最好的办法是使用[RehabMan](https://github.com/RehabMan/Laptop-DSDT-Patch)的工具选择[battery_Lenovo-X230i.txt](https://github.com/RehabMan/Laptop-DSDT-Patch/blob/master/battery/battery_Lenovo-X230i.txt)配置文件自己打一下补丁。具体教程可以自行搜索一下，非常简单。
> 
> 非常感谢你的回复，下面是我通过你回复并操作后得出的一些结果。
> 在更换DW1820A或者DW1560的情况下仍无法正常卡机，根据rehabman在反编译DSDT并修复电源后可正常启动，电源显示正常，估计是bios的问题或者为机型差异导致的问题。希望以上对你EFI的优化有帮助，再次感谢。
> 另外有个问题，我现在的键盘大小写灯经常无法正常指示状态，还有静音键的灯会常亮，偶尔FnLock也会常亮，请问你是否有类似情况呢。

我也和你一样，每次睡眠唤醒以后，fnlock灯常亮，fn被激活，而且无法取消fn，必须重启解决，希望早日有解决方案，e480就完美了。
