### ISSUE TITLE
安装时磁盘工具不显示硬盘

### ISSUE THREAD

**Issue by cosmt** [aliyoge/Hackintosh-ThinkPad-E480#8]
非常感谢您的分享，
我试着安装的时候找不到笔记本硬盘，
进入安装界面用磁盘工具格式化的时候只显示U盘，
另外我使用的是13版本，
这个问题有人遇到过吗？

**Comment by bailigege** [comment]
因为你是nvme 固态 我也是  不过我已经改完了

**Comment by cosmt** [comment]
> 因为你是nvme 固态 我也是 不过我已经改完了

能分享下是怎么修改的吗？谢谢
